### ISSUE TITLE
Geometric sound creation

### ISSUE THREAD

**Issue by cjavdev** [DougBlumeyer/Geometrhythm#2]
The widget with dots and lines seems tough. does that exists already? I see that as being one of the hardest parts.

Seems ambitious, but i have confidence that you can pull this off and have something awesome to show. Definitely taking a crack at that sound generator first would ease my concerns.

**Comment by cmloegcmluin** [comment]
It is complete and works like a charm, albeit missing some stretch features I'd like to get to.
