### ISSUE TITLE
Tags and likes

### ISSUE THREAD

**Issue by cjavdev** [DougBlumeyer/Geometrhythm#3]
It looks like phase 2 has tags and likes, I would save those until very last. In the beginning I would focus on getting a rhythm up and allowing people to comment. likeing, upvoting and tagging should all be after thoughts.

**Comment by cmloegcmluin** [comment]
In this case, "liking" is pretty critical insofar as it also serves to "add to your collection". 

But your point is well taken — I will definitely at least shift tagging back to phase 5 with voting.
